# Generated by Django 3.0.5 on 2023-04-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20230416_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='percentage',
            field=models.PositiveIntegerField(default=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
