# Generated by Django 3.0.5 on 2023-04-16 20:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_auto_20230417_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
