# Generated by Django 3.0.5 on 2024-03-22 06:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_course_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='access_code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
