# Generated by Django 3.0.5 on 2024-03-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_course_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='question_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_marks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
