# Generated by Django 3.0.5 on 2024-04-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_course_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
