# Generated by Django 3.0.5 on 2024-04-02 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0020_auto_20240402_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='exam_question_size',
        ),
    ]
