# Generated by Django 3.0.5 on 2024-04-10 07:02

from django.db import migrations, models
import exam.models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0021_remove_course_exam_question_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to=exam.models.get_image_path),
        ),
    ]
