# Generated by Django 3.0.5 on 2024-04-14 20:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0022_auto_20240410_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='exam_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
