# Generated by Django 3.0.5 on 2024-04-24 23:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0024_auto_20240415_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='entry_time',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='passing_percentage',
            field=models.PositiveIntegerField(default=75, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
