# Generated by Django 3.0.5 on 2024-04-25 01:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0025_auto_20240424_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='entry_time',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
