# Generated by Django 3.0.5 on 2024-04-24 23:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organization_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='mobile',
            field=models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(12), django.core.validators.RegexValidator('^[+]?[0-9]{9,12}$')]),
        ),
    ]
